name: BDMA Notes Generation

on:
  push:
    branches: [ main ]

jobs:
  generate_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          pip install beautifulsoup4
          pip install chardet

      # Install LyX and epstopdf
      - name: Install LyX and required utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y lyx texlive-font-utils

      # Generate files for each university and course
      - name: Generate university course files
        run: |
          for uni in $(ls -d */); do
            for course in $(ls -d $uni*/); do
              if [ -f "${course}LectureNotes/source/summary.lyx" ]; then
                pushd "${course}LectureNotes/source/"
                # Ensure the target directory exists
                mkdir -p "${GITHUB_WORKSPACE}/docs/$uni"
                
                # Generate HTML
                lyx --export html summary.lyx > /dev/null || echo "Failed: $uni$(basename $course) HTML"
                if [ -d "summary.html.LyXconv" ]; then 
                    mv "summary.html.LyXconv" "${GITHUB_WORKSPACE}/docs/$uni$(basename $course)_summary.html.LyXconv"
                    python $GITHUB_WORKSPACE/utils/adjust_image_size.py "${GITHUB_WORKSPACE}/docs/$uni$(basename $course)_summary.html.LyXconv/summary.html"
                else
                    lyx --export xhtml summary.lyx > /dev/null || echo "Failed: $uni$(basename $course) XHTML"
                    mkdir summary.html.LyXconv
                    mv *.png summary.html.LyXconv/
                    mv summary.xhtml summary.html.LyXconv/summary.xhtml
                    mv summary.html.LyXconv "${GITHUB_WORKSPACE}/docs/$uni$(basename $course)_summary.html.LyXconv"
                    python $GITHUB_WORKSPACE/utils/adjust_image_size.py "${GITHUB_WORKSPACE}/docs/$uni$(basename $course)_summary.html.LyXconv/summary.xhtml"
                fi

                # Generate PDF
                lyx --export pdf2 summary.lyx > /dev/null || echo "Failed: $uni$(basename $course) PDF"
                [ -f "summary.pdf" ] && mv summary.pdf "${GITHUB_WORKSPACE}/docs/$uni$(basename $course)_summary.pdf"
                popd
              fi
            done
          done

      # Move docs directory to a temporary location
      - name: Move docs to temporary location
        run: |
          mkdir -p /tmp/docs
          mv $GITHUB_WORKSPACE/docs/* /tmp/docs/

      # Commit and push changes to the docs directory in main branch
      - name: Commit changes to docs in main branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./docs/
          git commit -m "Update docs with latest lecture notes" || echo "No changes to commit"
          git push

      # Clean up workspace to allow for a fresh checkout
      - name: Cleanup Workspace
        run: git clean -xdf

      # Checkout the gh-pages branch with full history
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          fetch-depth: 0

      # Copy generated files from temporary location to gh-pages and commit
      - name: Deploy to gh-pages
        run: |
          mkdir -p universities
          cp -r /tmp/docs/* universities/

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Update lecture notes'
          branch: gh-pages
          add: './*'